resources:
  repositories:
  - repository: moc-cicd
    type: git
    name:  moc-cicd
    ref: main

  pipelines:
  - pipeline: _microsoft.moccli
    source: unknown-compliance\MOC\microsoft.moccli
    branch: master

  - pipeline: _cloudmanager
    source: unknown-compliance\AksHci\cloudmanager
    branch: master

  - pipeline: _cloud-operator
    source: unknown-compliance\cloud-operator
    branch: master

  - pipeline: _mgmtappl
    source: unknown-compliance\Appliance\mgmtappl
    branch: master

  - pipeline: _ad-auth
    source: unknown-compliance\Security\ad-auth
    branch: master

  - pipeline: _microsoft.wssdagent
    source: unknown-compliance\MOC\microsoft.wssdagent
    branch: master

  - pipeline: _microsoft.wssdcloudagent
    source: unknown-compliance\microsoft.wssdcloudagent
    branch: master

  - pipeline: _wssdtesting
    source: unknown-compliance\wssdtesting
    branch: master

  - pipeline: _akshci-staging
    source: unknown-compliance\PipelineSetup\dev-catalog
    branch: main

trigger: none

stages:
- stage: Build
  jobs:
  - template: build.yaml

# Republish the artifacts into a single combined artifact. This will be used in the test stages
# to download all the artifacts generated by the build. (See, `artifactoverride` below.)
- stage: Republish
  jobs:
  - job: Republish_Job
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        source: current
        path: $(Pipeline.Workspace)/_microsoft.wssdagent

    - publish: $(Pipeline.Workspace)/_microsoft.wssdagent
      artifact: _microsoft.wssdagent

- template: cicd/moc/moc-template.yaml@moc-cicd
  parameters:
    dependsonstage: Republish
    artifactoverride: '_microsoft.wssdagent'
